# Generated by Django 3.1.7 on 2021-08-20 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_cadastro')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='dt_atualizacao', null=True)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'db_table': 'author',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=255)),
                ('notice', models.TextField(db_column='notice')),
                ('author', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, related_name='notice_set', to='news.author')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_cadastro')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='dt_atualizacao', null=True)),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
                'db_table': 'notice',
                'ordering': ['id'],
            },
        ),
    ]
