"""
Django settings for portal-news project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from .base import *

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# import mongoengine
# mongoengine.connect(db='portal-news', host='localhost:27017', username='root', password='secret')

DATABASES = {
        'default': {
            'ENGINE': 'djongo',
            'NAME': 'portal-news',
            'HOST': '127.0.0.1',
            'PORT': 27017,
            # 'ENFORCE_SCHEMA': False,
            # 'CLIENT': {
            #     'host': 'mongodb+srv://<username>:<password>@<atlas cluster>/<myFirstDatabase>?retryWrites=true&w=majority'
            # }
        }
}